name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: java install
        uses: actions/setup-java@v4
        with: 
            java-version: 17
            distribution: temurin
      - name: grant gradlew permission
        run: chmod +x gradlew
      - name: build project
        run: ./gradlew build -x test
      - name: store project jar
        uses: actions/upload-artifact@v4
        with:
          name: jar creation
          path: build/libs/*.jar
